AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for creating a prod VPC with three subnets.'

Resources:

  ProdVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: 'Name'
          Value: 'ProdVPC'

  ProdWebServerSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: 'ProdVPC'
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: 'Name'
          Value: 'ProdWebServerSubnet'

  ProdAppServerSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: 'ProdVPC'
      CidrBlock: '10.0.2.0/24'
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: 'Name'
          Value: 'ProdAppServerSubnet'

  ProdDataBaseSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: 'ProdVPC'
      CidrBlock: '10.0.3.0/24'
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      Tags:
        - Key: 'Name'
          Value: 'ProdDataBaseSubnet'
